-- MySQL Script generated by MySQL Workbench
-- Thu Sep 14 11:40:53 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema securify
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema securify
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `securify` DEFAULT CHARACTER SET utf8 ;
USE `securify` ;

-- -----------------------------------------------------
-- Table `securify`.`data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `securify`.`data` (
  `carID` INT(11) NOT NULL,
  `time_stamp` TIMESTAMP NOT NULL,
  `temp` DOUBLE NULL DEFAULT NULL,
  `humidity` INT(11) NULL DEFAULT NULL,
  `odometer` DOUBLE NULL DEFAULT NULL,
  `GPS_long` DOUBLE NULL DEFAULT NULL,
  `GPS_lat` DOUBLE NULL DEFAULT NULL,
  `battery_status` INT(11) NULL DEFAULT NULL,
  `description` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`carID`, `time_stamp`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `securify`.`joblist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `securify`.`joblist` (
  `carID` INT(11) NOT NULL,
  `jobID` INT(11) NOT NULL,
  `keyID` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `registerID` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `isJobActive` TINYINT(1) NOT NULL,
  `time_stamp_created` TIMESTAMP NOT NULL,
  `time_stamp_lastupdated` TIMESTAMP NOT NULL,
  `isJobApproved` TINYINT(1) NOT NULL,
  `description` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `gps_long_requested` DOUBLE NOT NULL,
  `gps_lat_requested` DOUBLE NOT NULL,
  PRIMARY KEY (`jobID`),
  INDEX `carID` (`carID` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `securify`.`registercar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `securify`.`registercar` (
  `userID` INT(11) NOT NULL,
  `carID` INT(11) NOT NULL,
  `keyID` VARCHAR(25) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `registerationID` VARCHAR(25) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `nameAlias` VARCHAR(25) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `time_stamp_last_serviced` TIMESTAMP NOT NULL,
  `description` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `car_image_uri` TEXT NULL,
  PRIMARY KEY (`carID`),
  UNIQUE INDEX `email` (`keyID` ASC, `registerationID` ASC),
  INDEX `userID` (`userID` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `securify`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `securify`.`users` (
  `userID` INT(11) NOT NULL,
  `fname` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `lname` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `email` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `phone` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `pass_hashed` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `pass_salt` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `role` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `gps_lat` DOUBLE NULL,
  `gps_long` DOUBLE NULL,
  `isOnline` TINYINT NOT NULL,
  `userscol` VARCHAR(45) NULL,
  PRIMARY KEY (`userID`),
  UNIQUE INDEX `email` (`email` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `securify`.`r_users_registercar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `securify`.`r_users_registercar` (
  `users_userID` INT(11) NOT NULL,
  `registercar_carID` INT(11) NOT NULL,
  PRIMARY KEY (`users_userID`, `registercar_carID`),
  INDEX `fk_r_users_registercar_registercar1_idx` (`registercar_carID` ASC),
  CONSTRAINT `fk_r_users_registercar_users`
    FOREIGN KEY (`users_userID`)
    REFERENCES `securify`.`users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_r_users_registercar_registercar1`
    FOREIGN KEY (`registercar_carID`)
    REFERENCES `securify`.`registercar` (`carID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `securify`.`r_users_joblist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `securify`.`r_users_joblist` (
  `users_userID` INT(11) NOT NULL,
  `joblist_jobID` INT(11) NOT NULL,
  PRIMARY KEY (`users_userID`, `joblist_jobID`),
  INDEX `fk_r_users_joblist_joblist1_idx` (`joblist_jobID` ASC),
  CONSTRAINT `fk_r_users_joblist_users1`
    FOREIGN KEY (`users_userID`)
    REFERENCES `securify`.`users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_r_users_joblist_joblist1`
    FOREIGN KEY (`joblist_jobID`)
    REFERENCES `securify`.`joblist` (`jobID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `securify`.`r_registercar_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `securify`.`r_registercar_data` (
  `registercar_carID` INT(11) NOT NULL,
  `data_carID` INT(11) NOT NULL,
  PRIMARY KEY (`registercar_carID`, `data_carID`),
  INDEX `fk_r_registercar_data_data1_idx` (`data_carID` ASC),
  CONSTRAINT `fk_r_registercar_data_registercar1`
    FOREIGN KEY (`registercar_carID`)
    REFERENCES `securify`.`registercar` (`carID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_r_registercar_data_data1`
    FOREIGN KEY (`data_carID`)
    REFERENCES `securify`.`data` (`carID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
